Fix intermittent display access issue: su -l xhost + -> su -m xhost + Fix premature exit when auto-update-system has never been run

diff --git a/freebsd-update-notify b/freebsd-update-notify
--- a/freebsd-update-notify
+++ b/freebsd-update-notify
@@ -79,7 +79,8 @@ display_users=$(ps -aexwwj | grep "DISPLAY=$DISPLAY_ID" | awk '{ print $1 }' | s
 # Make sure root can access the local display
 # NetBSD laptop, quagga
 for user in $display_users; do
-    su -l $user -c 'env DISPLAY=:0 xhost +local:root' > /dev/null || true
+    # su -l fails intermittently under KDE + sddm
+    su -m $user -c 'env DISPLAY=:0 xhost +local:root' > /dev/null || true
 done
 
 if freebsd-update updatesready || \
@@ -97,7 +98,8 @@ if freebsd-update updatesready || \
 	    if su -l $user -c "env DISPLAY=:0 xwininfo -root" > /dev/null; then
 		# If we can access the display, start dialog
 		if su -l $user -c "/usr/local/bin/zenity --display=:0 --question --text='Updates are available.\nInstall and reboot now?'" > /dev/null; then
-		    previous_update_time=$(cat /usr/local/etc/auto-admin/last-system-update)
+		    # || true in case auto-update-system has never been run before
+		    previous_update_time=$(cat /usr/local/etc/auto-admin/last-system-update || true)
 		    su -l $user -c '/usr/local/bin/urxvt -e auto-update-system --pause --yes > /dev/null'
 		    new_update_time=$(cat /usr/local/etc/auto-admin/last-system-update)
 		else
